### ISSUE TITLE
Multimodul-Projekt erstellen

### ISSUE THREAD

**Issue by kiltz** [janetschel/drag-master#3]
AS IS: Das Projekt besteht nur aus einem Modul
AS SHOULD BE: Das Projekt sollte in sinnvolle Module geteilt werden

Zur Verbesserung der Wartbarkeit und zur Erleichterung der Wiederverwendung bestimmter Programmteile unterteilt man Projekte in unterschiedliche Module.
Im ersten Schritt wäre ein Modul "drag-utils" und ein "drag-gui" sinnvoll.

**Comment by janetschel** [comment]
merged and done
