### ISSUE TITLE
WIKI-Seite für Aufgabenbearbeitung anlegen

### ISSUE THREAD

**Issue by kiltz** [janetschel/drag-master#5]
AS IS: Der Ablauf wurde erklärt, ist aber nicht zum nachlesen ;-)
AS SHOULD BE: Erstelle ein WIKI-Seite für die einzelnen Schritte der Bearbeitung einer Aufgabe und kommuniziere ihre Existenz.

**Comment by ManuelWaelzlein** [comment]
Wiki Seite erstellt: https://github.com/janetschel/drag-master/wiki/Workflow
